apiVersion: v1
kind: PersistentVolume
metadata:
  name: single-node-rwo-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/single-node-share

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: single-node-rwo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi
  volumeName: single-node-rwo-pv

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: colocated-pods
spec:
  replicas: 3
  selector:
    matchLabels:
      app: colocated
  template:
    metadata:
      labels:
        app: colocated
    spec:
      nodeSelector:
        storage: sticky          # forces all replicas to that node
      containers:
        - name: app
          image: nginx:1.27-alpine
          volumeMounts:
            - name: data
              mountPath: /usr/share/nginx/html
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: single-node-rwo-pvc
