apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-uses-rwx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shareddemo
  template:
    metadata:
      labels:
        app: shareddemo
    spec:
      securityContext:
        fsGroup: 2000
        fsGroupChangePolicy: OnRootMismatch
      initContainers:
        - name: init-perms
          image: busybox:1.36
          command: ["sh","-lc"]
          args:
            - |
              set -eux
              # make sure the share is group-writable for GID 2000
              chgrp -R 2000 /share || true
              chmod -R g+rwX /share || true
          volumeMounts:
            - name: shared
              mountPath: /share
      containers:
        - name: web
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            allowPrivilegeEscalation: false
            capabilities:
              add: ["NET_BIND_SERVICE"]   # allow non-root to bind :80
          volumeMounts:
            - name: shared
              mountPath: /usr/share/nginx/html
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: shared-rwx
