name: Update Blue/Green Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update (e.g. v1.2.3)'
        required: true
        default: 'v1.2.3'
      update_blue:
        description: 'Update blue_version'
        required: false
        type: boolean
        default: false
      update_green:
        description: 'Update green_version'
        required: false
        type: boolean
        default: false

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install ruamel.yaml
        run: pip install ruamel.yaml

        
      - name: Update values.yaml preserving format
        run: |
          python3 <<EOF
          from ruamel.yaml import YAML

          yaml = YAML()
          yaml.preserve_quotes = True

          file_path = "values.yaml"
          version = "${{ github.event.inputs.version }}"
          update_blue = "${{ github.event.inputs.update_blue }}" == "true"
          update_green = "${{ github.event.inputs.update_green }}" == "true"

          with open(file_path) as f:
              data = yaml.load(f)

          if update_blue:
              data["blue_version"] = version

          if update_green:
              data["green_version"] = version

          with open(file_path, 'w') as f:
              yaml.dump(data, f)
          EOF

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Create PR using CLI
        run: |
          BRANCH="update-version-${{ github.run_id }}"
          git checkout -b $BRANCH
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add values.yaml
          git commit -m "Update blue/green version to ${{ github.event.inputs.version }}"
          git push origin $BRANCH

          gh pr create \
            --title "Update blue/green version to ${{ github.event.inputs.version }}" \
            --body "Automated version bump:\n- version: ${{ github.event.inputs.version }}\n- blue: ${{ github.event.inputs.update_blue }}\n- green: ${{ github.event.inputs.update_green }}" \
            --base "${{ github.ref_name }}" \
            --head "$BRANCH"
