name: Conditional YAML Compare

on:
  push:
    branches:
      - main

jobs:
  check-yaml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Compare two values in yaml
        id: compare-values
        run: |
          VALUE1=$(yq '.yourKey1' your-file.yaml)
          VALUE2=$(yq '.yourKey2' your-file.yaml)

          echo "Value1: $VALUE1"
          echo "Value2: $VALUE2"

          if [ "$VALUE1" = "$VALUE2" ]; then
            echo "Values are equal ✅"
            echo "yaml_value=$VALUE1" >> $GITHUB_ENV
          else
            echo "Values are NOT equal ❌"
          fi

      - name: Run if values are equal
        if: env.yaml_value != ''
        run: echo "🎉 Both values matched: ${{ env.yaml_value }}"

      - name: Run if values are not equal
        if: env.yaml_value == ''
        run: echo "⚠️ Values did not match, taking alternate path"
