apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-one
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-one
  template:
    metadata:
      labels:
        app: service-one
    spec:
      serviceAccountName: service-one-ksa  # 🔹 Attach Kubernetes Service Account
      containers:
      - name: service-one
        image: your-registry/service-one_app:latest
        ports:
        - containerPort: 8002
        env:
        - name: DB_HOST
          value: "YOUR-CLOUD-SQL-HOST"  
        - name: DB_NAME
          value: "YOUR-DATABASE"
        - name: DB_PORT
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: service-one-service
spec:
  selector:
    app: service-one
  ports:
  - protocol: TCP
    port: 8002
    targetPort: 8002
  type: ClusterIP
