apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-three
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-three
  template:
    metadata:
      labels:
        app: service-three
    spec:
      containers:
      - name: service-three
        image: your-registry/service-three_app:latest
        ports:
        - containerPort: 8000
        env:
        - name: PROMPT_ENGINE_URL
          value: "http://prompt-engine-service.default.svc.cluster.local:5001"  # 🔹 Use Kubernetes DNS for service discovery
---
apiVersion: v1
kind: Service
metadata:
  name: service-three-service
spec:
  selector:
    app: service-three
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalancer
